apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-test
  namespace: test
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webhook-test
        Image: divyanshuk/webhook:main46
        env:
        - name: WEBHOOK_TEST
          value: testing-webhook
        ports:
        - containerPort: 443
        volumeMounts:
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
        imagePullPolicy: IfNotPresent
      volumes:
      - name: certs-volume
        secret:
          secretName: webhook-secret

