apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "webhook.example.com"
  namespace: test
  labels:
    app: web
webhooks:
- name: "webhook.example.com"
  matchPolicy: Equivalent
  timeoutSeconds: 30
  namespaceSelector:
    matchLabels:
      environment: "testing"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  clientConfig:
    service:
      name: webhook-test
      namespace: test
      path: /mutate/webhook
      port: 443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ2RENDQXRDZ0F3SUJBZ0lVTzJzbnNTMXNmeHB6MjdocTRzVzg3UUk0T2Rzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RURUxNQWtHQTFVRUJoTUNTVTR4Q3pBSkJnTlZCQWdNQWsxSU1Rc3dDUVlEVlFRSERBSlFUakVOTUFzRwpBMVVFQ2d3RWJtOXVaVEVOTUFzR0ExVUVDd3dFYm05dVpURVpNQmNHQTFVRUF3d1FkR1Z6ZEdGd2FTNTBaWE4wCkxuTjJZekVUTUJFR0NTcUdTSWIzRFFFSkFSWUVibTl1WlRBZUZ3MHlNekV4TURJd09EVXhNalJhRncweU5qQTQKTWpJd09EVXhNalJhTUhVeEN6QUpCZ05WQkFZVEFrbE9NUXN3Q1FZRFZRUUlEQUpOU0RFTE1Ba0dBMVVFQnd3QwpVRTR4RFRBTEJnTlZCQW9NQkc1dmJtVXhEVEFMQmdOVkJBc01CRzV2Ym1VeEdUQVhCZ05WQkFNTUVIUmxjM1JoCmNHa3VkR1Z6ZEM1emRtTXhFekFSQmdrcWhraUc5dzBCQ1FFV0JHNXZibVV3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN3R1hUcHkzSnJMZU54bkt0eUQxd1lGOXNXQ0RZcXU2by9GNVVmeEtPYgoyVGtqZ04vNXpnK2V1SFNETWp3c2pubUo4OE1YTlJ3UkFYMlNBUnRadWtWN1FnWHZoaEVqVy9KNWtjWVFuSW9vCmUyc1RTNm55cjU2SDFSOGxoNm9oT2VwRmRkWnpxYkVNUjNOVFhaTmFIUnRqS0JVVDNPY1h0aHlkSGRxN0FMTHYKcHRyYy8vU1lqeFdoQnVkZ29oSzloanBaNmdMRHJucHM1cGx5N3VkRloxWmo5dWJNYTJibXNmY2VLR05PRWM0bwpIejhwdytPc1IwUXV5eHZMcGRWN25ZWkxxenhWVDZJRi9rNitsbjJLRDliNzFVYnhFSWM2bUZxSWVEMjJXY0l1CnJManJqZDNmM0tqelF6R1owUU5VWnJDUVhIak5Uc29KNTFSRlViVWMrU1JWQWdNQkFBR2pjREJ1TUIwR0ExVWQKRGdRV0JCU2VQUmdQaC9qekQ3Wkg4dzdqak85bmpjb2IrVEFmQmdOVkhTTUVHREFXZ0JTZVBSZ1BoL2p6RDdaSAo4dzdqak85bmpjb2IrVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQnNHQTFVZEVRUVVNQktDRUhSbGMzUmhjR2t1CmRHVnpkQzV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFVWNBRllVSGUzWUpJdGh6cWNmVmNGRjdYRjgKRTR2UStDMVRTNG1mRzg3eTBKNkV2dm0wWGQvRW1nQ055UUI2WlhqclZRZ0h6dGVPTjVUOG9GMmlKS3VSbVh3Tgp3WkpVR3ZVZjJaWndISHdIYmNHeXUwOW5NSEZzbno5Y2tVK3Z1dkRLTDhraUZWRWJPaW1HT1FwWHhKcGc5SDl1CjNGcUZOOGZHdWNBRXVhK2pwcG5FSGJZeHhNcy8yclRkeUF2V3RSTHpEZlF5a1gzanJaRTZPa3VLR2FiMW1jMEoKV0ZvSHowQ0xpSlJwTTZTVWRORHd2NzNDZEJvOHBnWUxWaWc1Vm9JMkcrZm1uaUFURXlkMVZJd2NhaEFZZXB6MApTYUQyNDhmQVRPVnN3ODlLNUd5NW8wZkRXbGdsZEtMdUNGMUk4aEh6aGVJVHk0S3F6dkVPSEoxZlNMcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - apiGroups: ["*"]
    resources:
    - "deployments"
    - "pods"
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE


