apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "testapi.example.com"
  namespace: test
  labels:
    app: web
# annotations:
# cert-manager.io/inject-ca-from: test/admission-tls
webhooks:
- name: "testapi.example.com"
  matchPolicy: Equivalent
  timeoutSeconds: 30
  # objectSelector:
  #   matchLabels:
  #     hello: "true"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  clientConfig:
    service:
      name: testapi
      namespace: test
      path: /mutate/deployments
      port: 443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ2RENDQXRDZ0F3SUJBZ0lVTzJzbnNTMXNmeHB6MjdocTRzVzg3UUk0T2Rzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RURUxNQWtHQTFVRUJoTUNTVTR4Q3pBSkJnTlZCQWdNQWsxSU1Rc3dDUVlEVlFRSERBSlFUakVOTUFzRwpBMVVFQ2d3RWJtOXVaVEVOTUFzR0ExVUVDd3dFYm05dVpURVpNQmNHQTFVRUF3d1FkR1Z6ZEdGd2FTNTBaWE4wCkxuTjJZekVUTUJFR0NTcUdTSWIzRFFFSkFSWUVibTl1WlRBZUZ3MHlNekV4TURJd09EVXhNalJhRncweU5qQTQKTWpJd09EVXhNalJhTUhVeEN6QUpCZ05WQkFZVEFrbE9NUXN3Q1FZRFZRUUlEQUpOU0RFTE1Ba0dBMVVFQnd3QwpVRTR4RFRBTEJnTlZCQW9NQkc1dmJtVXhEVEFMQmdOVkJBc01CRzV2Ym1VeEdUQVhCZ05WQkFNTUVIUmxjM1JoCmNHa3VkR1Z6ZEM1emRtTXhFekFSQmdrcWhraUc5dzBCQ1FFV0JHNXZibVV3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN3R1hUcHkzSnJMZU54bkt0eUQxd1lGOXNXQ0RZcXU2by9GNVVmeEtPYgoyVGtqZ04vNXpnK2V1SFNETWp3c2pubUo4OE1YTlJ3UkFYMlNBUnRadWtWN1FnWHZoaEVqVy9KNWtjWVFuSW9vCmUyc1RTNm55cjU2SDFSOGxoNm9oT2VwRmRkWnpxYkVNUjNOVFhaTmFIUnRqS0JVVDNPY1h0aHlkSGRxN0FMTHYKcHRyYy8vU1lqeFdoQnVkZ29oSzloanBaNmdMRHJucHM1cGx5N3VkRloxWmo5dWJNYTJibXNmY2VLR05PRWM0bwpIejhwdytPc1IwUXV5eHZMcGRWN25ZWkxxenhWVDZJRi9rNitsbjJLRDliNzFVYnhFSWM2bUZxSWVEMjJXY0l1CnJManJqZDNmM0tqelF6R1owUU5VWnJDUVhIak5Uc29KNTFSRlViVWMrU1JWQWdNQkFBR2pjREJ1TUIwR0ExVWQKRGdRV0JCU2VQUmdQaC9qekQ3Wkg4dzdqak85bmpjb2IrVEFmQmdOVkhTTUVHREFXZ0JTZVBSZ1BoL2p6RDdaSAo4dzdqak85bmpjb2IrVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQnNHQTFVZEVRUVVNQktDRUhSbGMzUmhjR2t1CmRHVnpkQzV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFVWNBRllVSGUzWUpJdGh6cWNmVmNGRjdYRjgKRTR2UStDMVRTNG1mRzg3eTBKNkV2dm0wWGQvRW1nQ055UUI2WlhqclZRZ0h6dGVPTjVUOG9GMmlKS3VSbVh3Tgp3WkpVR3ZVZjJaWndISHdIYmNHeXUwOW5NSEZzbno5Y2tVK3Z1dkRLTDhraUZWRWJPaW1HT1FwWHhKcGc5SDl1CjNGcUZOOGZHdWNBRXVhK2pwcG5FSGJZeHhNcy8yclRkeUF2V3RSTHpEZlF5a1gzanJaRTZPa3VLR2FiMW1jMEoKV0ZvSHowQ0xpSlJwTTZTVWRORHd2NzNDZEJvOHBnWUxWaWc1Vm9JMkcrZm1uaUFURXlkMVZJd2NhaEFZZXB6MApTYUQyNDhmQVRPVnN3ODlLNUd5NW8wZkRXbGdsZEtMdUNGMUk4aEh6aGVJVHk0S3F6dkVPSEoxZlNMcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  #    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1ekNDQXFNQ0ZCUDI2QVhXMzh5Qmh5S3NsV25ESWsrVmlYQ3dNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1oKTVFzd0NRWURWUVFHRXdKSlRqRUxNQWtHQTFVRUNBd0NUVWd4Q3pBSkJnTlZCQWNNQWxCT01Sa3dGd1lEVlFRSwpEQkIwWlhOMFlYQnBMblJsYzNRdWMzWmpNUmt3RndZRFZRUUxEQkIwWlhOMFlYQnBMblJsYzNRdWMzWmpNUmt3CkZ3WURWUVFEREJCMFpYTjBZWEJwTG5SbGMzUXVjM1pqTVI4d0hRWUpLb1pJaHZjTkFRa0JGaEIwWlhOMFlYQnAKTG5SbGMzUXVjM1pqTUI0WERUSXpNVEF6TVRFeU1EWXhOVm9YRFRJME1UQXpNREV5TURZeE5Wb3dnWmt4Q3pBSgpCZ05WQkFZVEFrbE9NUXN3Q1FZRFZRUUlEQUpOU0RFTE1Ba0dBMVVFQnd3Q1VFNHhHVEFYQmdOVkJBb01FSFJsCmMzUmhjR2t1ZEdWemRDNXpkbU14R1RBWEJnTlZCQXNNRUhSbGMzUmhjR2t1ZEdWemRDNXpkbU14R1RBWEJnTlYKQkFNTUVIUmxjM1JoY0drdWRHVnpkQzV6ZG1NeEh6QWRCZ2txaGtpRzl3MEJDUUVXRUhSbGMzUmhjR2t1ZEdWegpkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURhT0c0YzYxc2w2TlcwClo1cStNcmpXSThpSVhiaDVIUGdzWkxpa2lnS2pla2NadWFyeXFqZnBJQVdzUDIvZC94Y3BhVjBLZ3NCQmNwMXEKYzJVY1BSTTZUcXBvNWRUNXBDa0FRRVRmM3JQTjJ3Q3VJemhJT1hBRUU4ZkJMUUpqc0p5ZUtKaGI4T1BFUXRzUQpNN3VUM215NnFwY3Q1WklqcWoxRnlXYk92TWdtM0lPT0tJdDN5L1J4NEdOS0FkVU93SVl1VldLU3dneTVlV2hKCjZob3AvaUl6bWppUit5VDl1TEoya0lBeTNOVGlRc0VubEdRK2dIc0ZFeWswNHM1bzVKbHhIdUd2MmRkeCtmcnMKWFFTdzQxOUlOdzNUdldZVFNNRnNWUFd0TXUzcnZ0dVlGVDZuWE83R3p4T293ZnRWZ2w0Uk5CeStJeEUweVVGLwo3OW9VbzVoWEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU5RL0NzTVl5VllXdndUQnptZTQ0eXNoCkZqZUpZYmpUOFF1K2l2NXZvUkVIWXlOcStheit5YkxhMWtVM29BRjltVnpKOGUrUzZUTDFIZ2JSUlk3T0ZVRXMKQ2dETjg2UmZ6R1NtdW5BRE5oQk91ei9FRTBpM0NlcVNUOEdwam1CdXVKSWRLcVR1ZmNRZFNqSG5kY3dOeFJSYQpVUEdpQjNtcHdIS1Q3a3JHNHF3MW1SbDRvTStINDdjZ1hXbU5pamU3bHJEdkNLd3VJeHU4Q2x0VWlNVC9MUjdwCmpPM0FkUFAzUFdxUTQrcjVjeDZQdUFJL2RGanJ1T0JsVklrMTRYeGtKajRLbDhraTNDNHFHM0VUMzdMVWRDTEcKaXdFbXBZYjNKb3pvVVRMMXorZGsxaVRuaVpQcVd1SVplakt2V0MydVVpQ1N2R2lMTVNtS1RUWEdRdG5Mc0VBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== #t is needed because all Admission Webhooks need to be on SSL
  rules:
  - apiGroups: ["*"]
    resources:
    - "deployments"
    - "jobs"
    - "pods"
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE
  # namespaceSelector:
  #   matchLabels:
  #     mutate: enabled

