FROM python:3.6.9-alpine

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt

COPY validate.py /app

COPY wsgi.py /app

ENV WEBHOOK_TEST = "testing-webhook"

CMD gunicorn --certfile=/certs/mycertificate.crt --keyfile=/certs/myprivate.key --bind 0.0.0.0:443 wsgi:admission_controller