FROM python:3.6.9-alpine

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt

COPY validate.py /app

COPY wsgi.py /app

# COPY mycertificate.crt /certs/mycertificate.crt

# COPY myprivate.key /certs/myprivate.key

ENV TENANT_NAME=elc_tenant

CMD gunicorn --certfile=/certs/webhook.crt --keyfile=/certs/webhook.key --bind 0.0.0.0:443 wsgi:admission_controller

