apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "testapi.example.com"
  namespace: test
  labels:
    app: web
webhooks:
- name: "testapi.example.com"
  matchPolicy: Equivalent
  timeoutSeconds: 30
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  clientConfig:
    service:
      name: testapi
      namespace: test
      path: /mutate/deployment
      port: 443
    caBundle: <cert_key>
  rules:
  - apiGroups: ["*"]
    resources:
    - "deployments"
    - "jobs"
    - "pods"
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE


